# config.yaml

# --- Project Paths ---
PATHS:
  MODEL_DIR: "./trained_model"
  SAVE_PATH: "trained_agent_sdn.pth"
  PRETRAINED_GNN: "trained_gnn_recall_ospf.pth"
  CHECKPOINT_PATH: "trained_agent_mm1.pth"
  PRETRAINED_LSTM: "trained_lstm.pth"
  FINGERPRINT_BANK: "dataset/fingerprint_bank.pt"

# --- Model Dimensions ---
MODEL:
  GNN_DIM: 256
  LSTM_DIM: 128
  GNN_LAYERS: 6
  N_PACKETS: 30

# --- Training Hyperparameters ---
TRAINING:
  EPOCH: 50
  EPISODES_PER_TOPO: 800
  BATCH_SIZE: 32
  
  LR: 5.0e-6
  GAMMA: 0.99
  CRITIC_LOSS_COEF: 0.5
  MAX_GRAD_NORM: 0.5

# --- Environment & QoS Constraints ---
ENV:
  MAX_NODES_NUM: 14
  MIN_DELAY: 1.0
  MAX_DELAY: 200.0
  MIN_BW: 7.5
  MAX_BW: 90.0
  MAX_LOSS: 5.0