# config.yaml

# --- Project Paths ---
PATHS:
  PRETRAINED_DIR: "data/weights"
  PRETRAINED_LSTM: "trained_lstm.pth"
  PRETRAINED_GNN: "trained_gnn_recall_ospf.pth"
  PRETRAINED_MM1: None
  FINGERPRINT_BANK: "data/fingerprints/fingerprint_bank.pt"
  TOPOLOGY_FILE: "nsfnet_gravity.graphml"
  CHECKPOINT_DIR: "workspace/checkpoints/sdn/"
  FINALMODEL_DIR: "workspace/finalmodels/sdn/"
  TOPOLOGIES_DIR: "data/topologies/"
  LOG_DIR: "workspace/logs/"

# --- Model Dimensions ---
MODEL:
  GNN_DIM: 256
  LSTM_DIM: 128
  GNN_LAYERS: 6
  N_PACKETS: 30

# --- Training Hyperparameters ---
TRAINING:
  EPOCH: 900
  GAMMA: 0.99
  END_LOAD: 300
  START_LOAD: 20
  BATCH_SIZE: 10
  LR_HEADS: 5.0e-4
  MAX_GRAD_NORM: 0.5
  ENTROPY_END: 0.0005
  ENTROPY_START: 0.05
  LR_GNN_BODY: 1.0e-5
  CRITIC_LOSS_COEF: 0.5
  FLOWS_PER_TYPE_PER_EPOCH: 10  

ENV:
  MIN_BW: 7.5
  MAX_BW: 90.0
  MIN_DELAY: 1.0
  MAX_DELAY: 200.0

  MAX_LOSS: 5.0
  MAX_JITTER: 30.0
  MAX_NODES_NUM: 10

  REQUIRED_BW: 5

  QOS_REWARD_PARAMS : {
    'VOIP':      {'max_delay': 150.0, 'max_jitter': 30.0,  'ref_bw': 0.07, 'w': [0.4, 0.2, 0.3, 0.1]}, # D, J, L, B
    'GAMING':    {'max_delay': 60.0,  'max_jitter': 20.0,  'ref_bw': 0.01, 'w': [0.4, 0.4, 0.1, 0.1]}, # Delay/Jitter 核心
    'STREAMING': {'max_delay': 1000.0,'max_jitter': 100.0, 'ref_bw': 5.0, 'w': [0.1, 0.1, 0.3, 0.5]}, # Bandwidth 核心
    'DEFAULT':   {'max_delay': 100.0, 'max_jitter': 30.0,  'ref_bw': 1.0, 'w': [0.25,0.25,0.25,0.25]}
  }