# 路径配置
name:
    exp_name: "full_film_ppo_train"
path:
    warmup_path: "workspace/outputs/warmup_train/warmup_with_delay_bw/checkpoints/warmup_final.pt"
    graph_path: "data/topologies/train_film.graphml"
    fgprt_path: "data/fingerprints/fingerprint_bank.pt"
    output_dir: "workspace/outputs/full_film_ppo_train"

debug_mode: false

# 网络架构
model:
    edge_dim: 4
    node_dim: 9
    gnn_heads: 4
    gnn_layers: 6
    hidden_dim: 128
    fingerprint_dim: 2
    
    ablation_mode: "full" # 'full', 'vanilla_gnn', 'film_drl', 'vanilla_drl'
    
# 训练参数
train:
    lr: 0.0004
    clip_eps: 0.2
    max_steps: 20
    batch_size: 30
    ppo_epochs: 10
    max_epochs: 500
    save_interval: 2
    entropy_coef: 0.01
    checkpoint_keep_count: 2

    

# 环境与背景流
env:
    src_nodes: [0,]
    dst_nodes: [13,]

    max_loss: 5.0
    bg_duration: 600

    min_bw: 10
    max_bw: 100.0
    min_delay: 1.0
    max_delay: 200.0
    max_nodes_num: 20
    bg_cookie: 0xB000
    flow_cookie: 0xA000

    end_load: 0.0           
    start_load: 0.0      
    total_load_mbps: 0.0
 
    curriculum: true       

# QoS 奖励参数
qos_reward:
    penalty_dead_end: -5
    GAMING:
        max_delay: 80.0
        max_jitter: 20.0
        w: [3, 1, 0.5] # [delay, jitter, loss_rate]
    VOIP:
        max_delay: 150.0
        max_jitter: 50.0
        w: [3, 1, 0.5] # [delay, jitter, loss_rate]
    STREAMING:
        max_delay: 1000.0
        max_jitter: 100.0
        w: [0.1, 0.1, 3] # [delay, jitter, loss_rate]