# 路径配置
name:
    exp_name: "film_warmup_train"
path:
    fgprt_path: "data/fingerprints/fingerprint_bank.pt"
    output_dir: "workspace/outputs/warmup_train"

# 网络架构
model:
    edge_dim: 4
    node_dim: 9
    gnn_heads: 4
    gnn_layers: 6
    hidden_dim: 128
    fingerprint_dim: 2

# 训练参数
train:
    lr: 0.0004
    clip_eps: 0.2
    batch_size: 16
    save_interval: 2
    epochs: 1000
    checkpoint_keep_count: 2
    pos_weight: 3.0
    # 早停设置
    patience: 10
    min_delta: 0.001
    # 采样设置
    samples_per_epoch: 10000
